"""validator last_picked

Revision ID: de7ba335ad78
Revises: 8cc3ce4828a1
Create Date: 2024-04-16 12:32:41.635321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7ba335ad78'
down_revision: Union[str, None] = '8cc3ce4828a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validators', sa.Column('last_picked', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validators', 'last_picked')
    # ### end Alembic commands ###
