"""miner id str

Revision ID: e69b4d8aef4c
Revises: de7ba335ad78
Create Date: 2024-04-19 08:06:36.837886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69b4d8aef4c'
down_revision: Union[str, None] = 'de7ba335ad78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_variations', 'miner',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #
    op.drop_column('message_variations', 'miner')
    op.add_column('message_variations', sa.Column('miner', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.alter_column('message_variations', 'miner',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_index(op.f('ix__message_variations__miner'), 'message_variations', ['miner'], unique=False)
    # ### end Alembic commands ###
