"""validator is active

Revision ID: 962708f2911a
Revises: e69b4d8aef4c
Create Date: 2024-04-23 08:55:16.037529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '962708f2911a'
down_revision: Union[str, None] = 'e69b4d8aef4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validators', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validators', 'is_active')
    # ### end Alembic commands ###
