"""change vars

Revision ID: 88f9cfb9508a
Revises: c3382ec883cb
Create Date: 2024-04-11 08:53:41.581138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f9cfb9508a'
down_revision: Union[str, None] = 'c3382ec883cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_variations', sa.Column('reply', sa.String(), nullable=True))
    op.drop_column('message_variations', 'content')
    op.add_column('messages', sa.Column('prompt', sa.String(), nullable=True))
    op.drop_column('messages', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'prompt')
    op.add_column('message_variations', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('message_variations', 'reply')
    # ### end Alembic commands ###
